const UserJSON = [
  {
    firstName: "Alejandro",
    lastName: "González",
    email: "alejandro.gonzalez@example.com",
    isActive: true,
    username: "alejogonza",
    password: "hashed_password",
    role: "mesero",
    image: {
      data: "",
      contentType: "",
      url: true,
      link: "http://www.grupohidalgo.com.mx/imagenes/defaultAvatar",
    },
    creationDate: "2024-02-07T00:00:00Z",
    updateDate: "2024-02-07T00:00:00Z",
    age: 25,
  },
  {
    firstName: "Beatriz",
    lastName: "Lopez",
    email: "beatriz.lopez@example.com",
    isActive: true,
    username: "beatrizlopez",
    password: "hashed_password",
    role: "chef",
    image: {
      data: "",
      contentType: "",
      url: true,
      link: "http://www.grupohidalgo.com.mx/imagenes/defaultAvatar",
    },
    creationDate: "2024-02-07T00:00:00Z",
    updateDate: "2024-02-07T00:00:00Z",
    age: 30,
  },
  {
    firstName: "Carlos",
    lastName: "Martinez",
    email: "carlos.martinez@example.com",
    isActive: true,
    username: "carlosmartinez",
    password: "hashed_password",
    role: "cajero",
    image: {
      data: "",
      contentType: "",
      url: true,
      link: "http://www.grupohidalgo.com.mx/imagenes/defaultAvatar",
    },
    creationDate: "2024-02-07T00:00:00Z",
    updateDate: "2024-02-07T00:00:00Z",
    age: 40,
  },
  {
    firstName: "Drago",
    lastName: "Dominguez",
    email: "drago.do@example.com",
    isActive: true,
    username: "drago.do",
    password: "hashed_password",
    role: "admin",
    image: {
      data: "",
      contentType: "",
      url: true,
      link: "http://www.grupohidalgo.com.mx/imagenes/defaultAvatar",
    },
    creationDate: "2024-02-07T00:00:00Z",
    updateDate: "2024-02-07T00:00:00Z",
    age: 25,
  },
  {
    firstName: "Pepe",
    lastName: "Despidos",
    email: "pepe@example.com",
    isActive: false,
    username: "pepedes",
    password: "hashed_password",
    role: "cajero",
    image: {
      data: "",
      contentType: "",
      url: true,
      link: "http://www.grupohidalgo.com.mx/imagenes/defaultAvatar",
    },
    creationDate: "2024-02-07T00:00:00Z",
    updateDate: "2024-02-07T00:00:00Z",
    age: 40,
  },
];

export default UserJSON;
